# Generated by Django 5.0.7 on 2024-09-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Supplier',
            new_name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'size')},
        ),
    ]
