# Generated by Django 5.0.7 on 2024-09-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_stock_options_rename_supplier_product_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='imagen_default.png', upload_to='products', verbose_name='Foto del calzado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Suela', 'Suela'), ('camel', 'Camel'), ('Plata', 'Plata')], default='Negro', max_length=20, null=True, verbose_name='Color'),
        ),
    ]
